/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package beanan.spring.profile

import org.gradle.testkit.runner.GradleRunner
import java.io.File
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'beanan.spring.profile.greeting' plugin.
 */
class GradleSpringProfilePluginFunctionalTest {
    @Test fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle.kts").writeText("")
        projectDir.resolve("build.gradle.kts").writeText("""
            plugins {
                java
                id("beanan.spring.profile.greeting")
            }
        """)

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("clean", "build")
        runner.withProjectDir(projectDir)
        val result = runner.build();

        // Verify the result
//        assertTrue(result.output.contains("Hello from plugin 'beanan.spring.profile.greeting'"))
        assertTrue(result.output.contains("start match"))

    }
}
