/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package beanan.spring.profile

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test


class GradleSpringProfilePluginTest {
    @Test fun `plugin replace task`() {
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("beanan.spring.profile")
    }
}
