/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package beanan.spring.profile

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'beanan.spring.profile.greeting' plugin.
 */
class GradleSpringProfilePluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("beanan.spring.profile.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
