name: publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: upload
        run: ./gradlew clean publishPlugins -Pgradle.publish.key=${{secrets.P_USERNAME}} -Pgradle.publish.secret=${{secrets.P_PASSWORD}}